### ISSUE TITLE
Only copy relative path when copied

### ISSUE THREAD

**Issue by Daniel15** [atom/status-bar#104]
I'm using Nuclide with a project on a remote server, but I believe this applies to local projects too. Let me know if this is specific to Nuclide though.

---

The path of the current file relative to the current project is displayed in the Atom status bar, which is really useful. However, clicking it copies the *absolute* path, not the relative one:
![Screenshot of issue](https://cloud.githubusercontent.com/assets/91933/9725580/76504f76-559b-11e5-82e0-56f44a62e3ac.png)

In my case at least, 99% of the time when I copy the path all I want is the relative path. Is it possible to add an option to make clicking the file name copy the relative path (ie. what's displayed in the status bar) rather than the full path?

**Comment by 50Wliu** [comment]
@batjko @kubetz

**Comment by batjko** [comment]
Something like `shift-click` could get the relative path, I suppose.
This could be done together with #101, but I have very little time these days and might only get to it in a week or two.

Perhaps @kubetz (or somebody else) can do it faster?
If not, I'm definitely happy to look at this as well, might just take a little while.

**Comment by awans** [comment]
Hey all, I've taken a crack at implement it. This is my first atom contribution so please don't hesitate to tell me if I've done something wrong here!

**Comment by thedaniel** [comment]
@atom/feedback I am hesitant to use such a potentially 'valuable' binding for something that's just a slight variation on the existing behavior, and I am slightly :-1: on this functionality being included at all. 
In general I think we could save ctrl-click for something a little more powerful down the road - "open in finder" "reveal in tree view" or "open on github" spring to mind.

I'm not sure why but if we *do* want this I feel like shift-click is a more natural 'slight variation on existing action' in the same way that pressing shift while typing a letter just produces a variation on the letter, but the other modifier keys tend to have actions separate from just text input.

Thoughts? I'm down to be talked into loving this feature but personally need a little convincing. @Daniel15  - what situations do you use click-to-copy on the filename, and where are you pasting the path? When I use it I am almost always pasting it into a terminal command, where an abs path is fine.

**Comment by awans** [comment]
Completely happy to use `shift+click` instead. I'll take another pass at this tonight..

I want the relative path when I want to:
- refer precisely to the file to a co-worker over chat
- access the file on a remote server (also pasting into a terminal)

In both cases it's much easier to have `project/code/path/file.py` than `/Users/awans/project/code/path/file.py`

**Comment by awans** [comment]
(I've updated the PR to use shift-click now)

**Comment by dwelle** [comment]
Shouldn't #118 be released by now? Can anyone confirm `shift+click` is copying relative path on windows? I'm on `1.1.2` and it doesn't seem to work for me.

**Comment by lee-dohm** [comment]
Yes, #118 was released in v0.83.0 of status-bar and is available in the current stable release of Atom, v1.6.0. I also just confirmed that it works using <kbd>Shift+Click</kbd> on Atom v1.6.0 on Mac OS X 10.11.3.

Thanks everyone!

**Comment by dwelle** [comment]
I can confirm that on `1.7.0-beta0` __Windows 7__ it doesn't work.

**Comment by Daniel15** [comment]
Yeah, this is not working for me on Windows either, although it does work for remote Nuclide projects as well as Mac OS X. Opened #135 to track that separately.

**Comment by zinkkrysty** [comment]
How can we make this more easily discoverable? I was about to file a similar issue as this one as I couldn't figure out the shift+click shortcut.

An idea could be is to have this text inside the tooltip "Click to copy absolute file path (Shift + Click for relative path)"
