### ISSUE TITLE
Not-quite-clicking on the path generates “copied” feedback; doesn't follow through

### ISSUE THREAD

**Issue by izuzak** [atom/status-bar#106]
_From @steveluscher on October 9, 2015 22:4_

# Repro

1. Hover your mouse just outside the pathname at bottom left
2. Click; note that a tooltip appears saying the path has been copied to the clipboard
3. Paste.

# Expected

The path is pasted.

# Actual

The path was never actually copied.

*Note: Hovering over the path such that the underline appears yields the desired behavior.*

_Copied from original issue: atom/atom#9100_

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.7.0-dev-f48069c.  @steveluscher can you please try again on Atom 1.6.0?

**Comment by steveluscher** [comment]
This easily reproduces in Atom 1.5.3, but not in 1.6.0. Close away!

**Comment by lee-dohm** [comment]
Thanks @steveluscher for following up!
