### ISSUE TITLE
File path copied with Linux/Unix style on Windows

### ISSUE THREAD

**Issue by izuzak** [atom/status-bar#113]
_From @niall83 on November 16, 2015 17:23_

In the status bar at the bottom of the editor window it displays the path for the currently open file e.g. C:\test\test.txt.

When I click on it, in order to copy the path to the clip board it copies with a Linux/Unix style path even though I'm using Windows:
/test/test.txt

![image](https://cloud.githubusercontent.com/assets/15875346/11189156/949f974e-8c86-11e5-897f-b6cdff20624a.png)

_Copied from original issue: atom/atom#9632_

**Comment by 50Wliu** [comment]
Confirmed...on Windows!

**Comment by dwelle** [comment]
WTBS, I actually prefer unix style even on windows. I'm using git-bash and windows style paths would require quoting -- so it'd be great if we could customize it when we align the package to windows-style.
