### ISSUE TITLE
Status Bar occasionally does not detect branch changes

### ISSUE THREAD

**Issue by 50Wliu** [atom/status-bar#128]
Sometimes when switching branches, Status Bar fails to notice that the branch changed, even though the file contents updated correctly.  Switching files, opening a new file, saving the file, etc. will cause Status Bar to realize its mistake.

You may need to switch branches a couple of times before this occurs.  I haven't found a reliable reproduction method yet.

Reproduced in safe mode on Windows 10 x64, Atom 1.7.0-dev-8472f91.

/cc @joshaber

**Comment by objectkit** [comment]
Apologies for commenting on a closed thread, but it is a frustrating issue. Please redirect me as necessary. Working from terminal within Atom, if I switch branch, rename branch, commit... I have to bring an another app into focus, then bring Atom back into focus in order for the current branch to update in tree-view and in status bar.... I would have expected this to have been automatic behaviour without need of switching app focus. I have been trying to locate the cause of this issue, but I am beginning to think that it could be this package. Thoughts?
