### ISSUE TITLE
Shift+Click to copy relative path doesn't work on Windows

### ISSUE THREAD

**Issue by Daniel15** [atom/status-bar#135]
Shift+Click on the path in the status bar to copy the relative path was added in #104/#118, but this functionality doesn't appear to work on Windows.

My test results on Atom v1.6.0:

 - Mac OS X, local project: Shift+Click works, copies relative path
 - Windows, remote project on Linux server (via Nuclide): Shift+Click works, copies relative path
 - Windows, local project: Shift+Click **doesn't work**, behaves the same as regular click. Copies absolute path in strange format with drive letter missing (`/src/foo/bar` rather than `c:\src\foo\bar`)

The toolbar itself has no trouble showing the relative path, it's just shift+click that has issues with it:
![image](https://cloud.githubusercontent.com/assets/91933/13901768/9aceaf3a-edeb-11e5-97ff-fa6e37ed1b17.png)

It seems like the code to determine the relative path in the toolbar must be different to the code to determine the relative path when shift-clicking.

**Comment by mnquintana** [comment]
Can you reproduce this after quitting Atom completely and reopening in safe mode? (`atom --safe`)

**Comment by Daniel15** [comment]
@mnquintana - Yes, this still happens in safe mode

**Comment by 50Wliu** [comment]
Confirmed on Windows.
