### ISSUE TITLE
Switch Git Branches via Status Bar

### ISSUE THREAD

**Issue by MartinMuzatko** [atom/status-bar#137]
The Status Bar could be so much more powerful.
Having a possibility to switch branches via the branch display would be a lot easier and intuitive.

Please add any concerns you have about this feature request.

Thanks in advance

**Comment by thomasjo** [comment]
My initial concern is that this will open a flood gate of similar, perhaps ancillary feature requests;
 1. Make it possible to create a new branch, and switch to it.
 2. Make it possible to rename branches.
 3. Make it possible to delete branches.
 4. Make it possible to check out remote branches.
 5. etc.

Don't get me wrong, your suggestion, and mine, are not really a problem to implement. But I do fear that this would increase the responsibility of this package way outside of what is should do. If we were to go down this route, we should extract the git branch functionality in this package as a separate package. Doing that probably makes sense regardless.

**Comment by 50Wliu** [comment]
Please see #94 for the relevant PR.

**Comment by thomasjo** [comment]
Would be great with some additional :eyes: on this (in conjunction with #94). I stand by my concerns listed earlier, and strongly propose that we extract the existing git branch stuff into a separate package. Then we can implement branch switching and what not either in the new package, or in a community package.

/cc @atom/feedback

**Comment by MartinMuzatko** [comment]
Thanks a lot for your effort. I understand your concerns @thomasjo

**Comment by danielbayley** [comment]
> Having a possibility to switch branches via the branch display would be a lot easier and intuitive.

[git-plus](https://atom.io/packages/git-plus) does this incidentally…

**Comment by astorije** [comment]
I believe that this is now possible by default in a more recent version of Atom (at least, I can in 1.18.0):

<img width="391" alt="screen shot 2017-07-14 at 17 01 42" src="https://user-images.githubusercontent.com/113730/28230715-328d815c-68b6-11e7-9780-1d5837274639.png">

**Comment by danielbayley** [comment]
Yeah this [and more] is in https://github.com/atom/github now… so should probably be closed.

**Comment by 50Wliu** [comment]
Yep, this is now part of the github package.

**Comment by jgaibor** [comment]
Hello, in the last version, I can't switch to the others branches.

**Comment by lee-dohm** [comment]
@jgaibor If you're having a problem with the [github package](https://github.com/atom/github), please file a new issue there and completely fill in the template.
