### ISSUE TITLE
Display notifications in the status bar as Sublime

### ISSUE THREAD

**Issue by raky291** [atom/status-bar#153]
Display notifications in the status bar as Sublime.
Here are some basic examples:
![sublime](https://cloud.githubusercontent.com/assets/12045722/16130892/7fae8b58-33c8-11e6-94fe-fe5c89b9ac49.jpg)

**Comment by lee-dohm** [comment]
Thanks very much for the feedback and idea. The status bar is already getting kind of crowded on small screens with what we have in there. We're not looking to add this kind of feature at this time. Something like this could be added as a community package though! You may want to suggest something like this on [Discuss, the official Atom message board](https://discuss.atom.io).

Thanks again your contribution!
