### ISSUE TITLE
Git branch and status are not displayed

### ISSUE THREAD

**Issue by CostGranda** [atom/status-bar#174]
The current git branch and status are not displayed in the status bar.

**Reproduction Steps:**

1. Clean atom and git installation.
2. Git client installation and repo cloned.
3. Test in safe mode.
4. Uninstall git, atom and deleted `.atom` and `C:\Users\octocat\AppData\Local\atom` folders.
5. Back to step one.

**Screenshots and GIFs**

![image](https://cloud.githubusercontent.com/assets/5617032/19378297/716b57fa-91b1-11e6-8a16-7bb7f8202f56.png)

**Expected result:**
![image](https://cloud.githubusercontent.com/assets/5617032/19378425/1d1633ae-91b2-11e6-966a-c3c6b035d1f3.png)

**Atom version:**
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**OS and version:** Windows 10pro x64

**Installed packages:**

Community Packages (1) C:\Users\coste\.atom\packages
└── chester-atom-syntax@0.1.1

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by damieng** [comment]
Trying to repro this but not able to yet.

![image](https://cloud.githubusercontent.com/assets/118951/19394919/0369df08-91f0-11e6-878b-13f579034269.png)

Windows 10, Atom 1.11.1 with status-bar 1.6.0. Correctly showing in both normal and safe mode here. Must be another factor involved.

**Comment by damieng** [comment]
It appears your .git folder is in the properties folder? Atom only treats the top-level containing folder as a git repo so you'd need to open Properties.

**Comment by CostGranda** [comment]
This is the directory scheme 
![image](https://cloud.githubusercontent.com/assets/5617032/19396473/e5b0f9ce-9208-11e6-96ee-d035431bd9e1.png)
PapeleriaTPA is a netbeans project inside the git repo.

**Comment by CostGranda** [comment]
@damieng I have installed the [1.10.0](https://github.com/atom/atom/releases/tag/v1.10.0) version and now it works, don't know what happened

**Comment by damieng** [comment]
In the screenshot it shows you opened the GitHub folder not the paperleria folder.

Atom will only switch on the git integration when opening the folder that directly contains the .git subfolder. i.e. opening paperleria should work, opening GitHub or Scripts would not.

**Comment by CostGranda** [comment]
Thank you so much @damieng, I feel so stupid for that, I have never noticed that. Case closed.

**Comment by KapilMetacube** [comment]
Hello, is the git status that shows the line diff like **`+3,-2`** deprecated by the package.
Because I do not see it anymore.
Atom version: 1.21.1

However, I have noticed it from much earlier versions but never reported and now I kind of missing it.

**Comment by rsese** [comment]
See https://github.com/atom/github/issues/1035 for more details about that @KapilMetacube.

**Comment by KapilMetacube** [comment]
Thanks, @rsese.
