### ISSUE TITLE
status-bar is deprecated.

### ISSUE THREAD

**Issue by obliviga** [atom/status-bar#191]
You have the core package "status-bar" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:32)
```

**Comment by damieng** [comment]
This is not a bug but a user error.  Please use `apm remove` to remove your user-installed version of status-bar which will then use the bundled version.
