### ISSUE TITLE
It'd be nice to have a character count of selected text

### ISSUE THREAD

**Issue by joshdcomp** [atom/status-bar#21]
I can only speak to seeing this in the wild via Coda, but I know that when I highlight text, in the same area that it gives line/column position, it also gives a character count of the selected text. 

So it would be something like: `[line]/[col] ([count])`

**Comment by johnyf** [comment]
There is also the https://atom.io/packages/wordcount package. It displays a count of both the number of characters and words in the selected text, or of the entire file, if no text is selected.
