### ISSUE TITLE
Remove icon offset?

### ISSUE THREAD

**Issue by matthewwithanm** [atom/status-bar#212]
Currently, the status bar [is shifting all icons placed in it a pixel down][1]. This seems a little overbroad because of how broad the selector is (it applies to all descendants). Should it be removed?

[1]: https://github.com/atom/status-bar/blob/7f7a74ac966552ade9432031c80fc3bafe557222/styles/status-bar.less#L81-L82

**Comment by simurai** [comment]
Hmm.. In the One themes it gets [overridden](https://github.com/atom/one-dark-ui/blob/f4f9fa94841fc9fa5554201f146c8523f2b6cb7a/styles/status-bar.less#L55). But it would affect some themes. Like `atom-dark-ui`:

![status-bar](https://user-images.githubusercontent.com/378023/33705508-f1362af2-db73-11e7-9c44-0684d0af666f.gif)

@matthewwithanm did you run into an issue where icons got nested?

**Comment by matthewwithanm** [comment]
Oh, I bet this is a precedence issue because I'm running status-bar from source (dev) and not the theme. 🤔

**Comment by matthewwithanm** [comment]
I guess I'll close this…the precedence issue makes it hard for development but it's not a general issue. Thanks @simurai (:
