### ISSUE TITLE
panel with arrows and buttons (fetch, pull, push) disappeared on git-submodule path

### ISSUE THREAD

**Issue by patriciussanctus** [atom/status-bar#219]
### Description
panel with arrows and buttons (fetch, pull, push) disappeared into git-submodule project.
only in git-submodule project not working, in base project working!
hotkeys of git-plus working, i can fetch, pull and push in git-submodule project.
how i can test and check workable, or enable, or debug this?

### Steps to Reproduce
after update or other manipulations, i know not =(

![atom-status-problem](https://user-images.githubusercontent.com/16253399/34871790-efcaadbc-f79f-11e7-819e-891896c6f9c8.jpg)

this panel missing.
<img width="412" alt="this-panel" src="https://user-images.githubusercontent.com/16253399/34871798-f334988c-f79f-11e7-8e5f-95fcfaed8397.png">

### Versions
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3
macOS High Sierra 10.13.2

**Comment by 50Wliu** [comment]
Please report this to the [github](https://github.com/atom/github) package instead, which controls when the push/pull status bar icons are shown.  Thanks!
