### ISSUE TITLE
Feature Request: Move status bar to Apple TouchBar

### ISSUE THREAD

**Issue by ProLoser** [atom/status-bar#221]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It would be amazing if the atom status bar could be completely hidden from my screen and instead relocated to the TouchBar.

**Comment by damieng** [comment]
We have decided to leave that up to individual package authors to support hardware-specific features such as this - we covered it here https://github.com/atom/atom/issues/15206
