### ISSUE TITLE
"Not on branch" message on status bar after creating or cloning a repository

### ISSUE THREAD

**Issue by OsLivon** [atom/status-bar#230]
![capturar](https://user-images.githubusercontent.com/4340871/47765253-5bb62100-dcc9-11e8-80e4-9f9e64884f32.PNG)
![capturar1](https://user-images.githubusercontent.com/4340871/47765261-607ad500-dcc9-11e8-84e8-d775b45989dd.PNG)

### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open Atom
2. File>Add Project Folder
3. Create a Git repository by hiting Ctrl + Shift + 9 to open the Git tab, click on Create repository, and then click Init

**Expected behavior:** [What you expect to happen]
Create a git repository and the branch master by the default

**Actual behavior:** [What actually happens]
On status bar it appears Not on branch, and when click on the branch icon, and then New Branch, write the name of a branch and hit Enter in order to create a branch, no branch is created.

**Reproduces how often:** [What percentage of the time does it reproduce?]
I've recently installed Atom and since it acts like this.

### Versions
Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

OS: Windows 10

Thanks

**Comment by rsese** [comment]
Thanks for the report!  I think this is expected - for example, this is what I see using git commands:

```
$ git init
Initialized empty Git repository in /Users/rsese/sandbox/test/.git/

$ git branch

$ git branch new-branch
fatal: Not a valid object name: 'master'.

$ git add test.txt

$ git commit -m "Initial commit"
[master (root-commit) 784d112] Initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt

$ git branch
* master

$ git branch new-branch

$ git branch
* master
new-branch
```

So that first `git branch` doesn't list `master` until after the first commit and you can't create a new branch until after your first commit.

With the GitHub package, it looks like it behaves the same way - if you stage and commit something after initializing the repository, then the branch drop down shows it's on `master` and you can start creating branches.

Since things seem to working as expected we'll go ahead close but let me know if I misunderstood anything.
