### ISSUE TITLE
Copy Path from bottom Status Bar

### ISSUE THREAD

**Issue by davidbarratt** [atom/status-bar#29]
Hello!

Reopening atom/atom#2973 here. :)

Thanks!

**Comment by aoghina** [comment]
+1, this would be really useful

**Comment by eaviles** [comment]
Any news about this?

**Comment by mnquintana** [comment]
None of the core team or maintainers are working on this right now, but PRs are always welcome!

**Comment by eaviles** [comment]
I may be interested in helping with this :)
How can I learn more about how to start helping?

**Comment by mnquintana** [comment]
@eaviles You can start by taking a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) and feel free to post any questions on [Discuss](https://discuss.atom.io/) or Slack. Basically, to work on a core package you can follow these steps:

1. Fork the repo
1. `git clone your-fork-goes-here`
1. `apm link -d` in the directory of your locally cloned repo
1. Open Atom in dev mode (`atom -d` or View > Developer > Open in Dev Mode)

These steps will load the dev version of the package so you can test it directly in an Atom window. Whenever you make a change to the code and want to see it reflected in the window, just look for `Window: Reload` in the Command Palette and that will reload the window (and your changes).

You can start by writing a failing spec in the `spec/` directory testing the feature (ie. what you would expect to happen when clicking on the path in the status bar). Then you can start implementing it (I think it would be in https://github.com/atom/status-bar/blob/master/lib/file-info-view.coffee). You'll probably want to take a look at the [Clipboard API](https://atom.io/docs/api/v0.205.0/Clipboard) for this feature.

Hope that helps!

**Comment by eaviles** [comment]
@mnquintana Amazing! thanks I will definitively give it a try.

**Comment by 50Wliu** [comment]
Solved by #28.  This should be available in the next Atom version, 1.0.1.

**Comment by eaviles** [comment]
Cool @50Wliu, thanks for the update.
