### ISSUE TITLE
Not showing git info (ubuntu)

### ISSUE THREAD

**Issue by voylinux** [atom/status-bar#50]
Not showing info (looks like not working) after todays fresh install building from source on Linux (Ubuntu 64 bits).
It is actually enabled but showing nothing.

**Comment by voylinux** [comment]
Showing now. Seems like the editor is not always detecting the branch I am working in.
Twice restarted.

**Comment by benogle** [comment]
Are you opening the root of the git repo? It can only detect when at the root of the git repo.

**Comment by voylinux** [comment]
Not sure, really. If it happens again I will check.
