### ISSUE TITLE
status-bar.prependRight is deprecated.

### ISSUE THREAD

**Issue by atalargo** [atom/status-bar#69]
* Atom version  : 0.190.0
* status-bar version : 0.67.0

Use ::addRightTile({item, priority}) instead.
```
status-bar.prependRight (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:125:12)
[object Object].prependRight (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/main.js:52:36)
```

**Comment by maxbrunsfeld** [comment]
@atalargo can you report which packages you have installed (`apm list`)?

**Comment by izuzak** [comment]
@maxbrunsfeld Just wanted to mention why I tagged this with `atom` -- I suspected that a package was causing this as well, but it found it strange that deprecation cop pointed to status bar, and not to that package. This reminds me of https://github.com/atom/atom/issues/6310.

**Comment by maxbrunsfeld** [comment]
Yeah, it seems like a bug in our deprecation system. I'm not sure why the stack trace is so short in this case. I'm hoping we can reproduce this problem if we find out what packages @atalargo was using.

**Comment by kevinsawicki** [comment]
> I'm not sure why the stack trace is so short in this case.

https://github.com/atom/grim/pull/4 started limited the depth to 3

**Comment by maxbrunsfeld** [comment]
Oh that's right. So we just need to move the Grim call out by one level. I'll do that.
