### ISSUE TITLE
status-bar-right is floated

### ISSUE THREAD

**Issue by braver** [atom/status-bar#72]
I'm dealing with some [layout irregularities in Zen](https://github.com/defunkt/Zen/issues/55) w/r the status-bar and I noticed that the right halve of the status bar still uses the `pull-right` class which floats it to the right. With an `!important` even. Wouldn't it be cleaner to use `align-self: flex-end`? That would coincidentally also solve my problem :) Is this a design decision or just some Bootstrap left-over? @simurai?

**Comment by simurai** [comment]
Looks like a left-over. The left part is flexible and already pushes the right part to the right. So the `pull-right` class can probably get removed. Although saw that the One theme uses that selector, but can be changed.
