### ISSUE TITLE
Include a tooltip for every icon without a label

### ISSUE THREAD

**Issue by Alhadis** [atom/status-bar#81]
#### Description
Opened a file, saw this in the bottom-right corner:

![huh](https://cloud.githubusercontent.com/assets/2346707/7999015/579a0264-0b88-11e5-93f1-36a3e0070972.png)
Had no idea what it was trying to tell me, and no tooltip was available, either. I resorted to kicking open the developer tools, inspecting the icon in the console, and checking the class attribute to ascertain its purpose.

I'd add a tooltip for that icon, as well as anything else that indicates something that mightn't be immediately apparent to the user. Sure, it might be obvious after clicking it, but it's generally not good practice in UX to encourage users to press something in order to understand its purpose.

![erm](https://cloud.githubusercontent.com/assets/2346707/7999127/b7d55a42-0b89-11e5-9c71-1da8accb245d.png)

I'd also make the deprecation cop use the same visual cue (pointer cursor, underlined text, etc) as the language and encoding menus. I understand that's a menial issue, though, and one that's better off being filed as a separate issue in the appropriate repo.

#### Specs
 - **Platform:** Mac OS/X 10.9.5 (Screw Yosemite)
 - **Processor:** 2.3 GHz Intel Core i7
 - **Memory:** 16 GB 1600 MHz DDR3
 - **Atom version:** 0.206.0

**Comment by jerone** [comment]
:+1: on a more user-friendly interface.

**Comment by mnquintana** [comment]
:+1: I totally support this. I distinctly remember back when I first started using Atom being especially confused by the git status icons in the status bar.

**Comment by 50Wliu** [comment]
What does that icon mean, anyway?

**Comment by mnquintana** [comment]
I think it's number of un-comitted insertions and deletions?

**Comment by 50Wliu** [comment]
Sorry, meant the first picture in the initial issue (unless that's the same thing? :confused:).

**Comment by jerone** [comment]
It think it means no source changes.

**Comment by Alhadis** [comment]
Heh, see? You're all confused as well! There's absolutely no indication as to what it means. =)

The icon is, to my understanding, something to tell the user the current file's being ignored by version control (that is, it matches a path specified in a local `.gitignore`). That never would've occurred to me because I wasn't editing something in a repo (it was actually live file-editing over FTP using FileZilla, so it resided in a temp directory somewhere).

@mnquintana : Yup, you're right about the uncommitted insertions/deletions. =) Again, something that could be made less nebulous with a tooltip.
