### ISSUE TITLE
Clicking on links in status bar focuses them

### ISSUE THREAD

**Issue by mnquintana** [atom/status-bar#82]
Not quite sure if this counts as a bug or enhancement, but I've noticed that clicking on any links in the status bar focuses them, when it should keep focus on whatever was focused before clicking on them. However, the correct element is focused if you dismiss the modal by clicking away from it.

![untitled](https://cloud.githubusercontent.com/assets/823545/8008397/e91e2094-0b6f-11e5-9a6e-1c14f99bdc89.gif)

Atom 0.206.0

**Comment by Abdillah** [comment]
This is critical for any veteran emacs user. They might say, "No :mouse: should be required."
Although, pressing <kbd>Tab</kbd> several time return the cursor to `TextEditor`.
