### ISSUE TITLE
Rearrange Status Bar to the Bottom Panel

### ISSUE THREAD

**Issue by alefragnani** [atom/status-bar#91]
Would be interesting to have the Status Bar shown in the bottom of Atom window, instead of the bottom of the Editors.

I posted this question in Atom Discussion https://discuss.atom.io/t/rearrange-status-bar-to-the-bottom-panel/18597/2 and @mnquintana asked me to add an issue to that. 

Thanks

**Comment by stephanos** [comment]
I agree.

A layout like this
```
 _________________________________
| file  | text area              |
| tree  |                        |
|       |                        |
|       |                        |
|       |                        |
|--------------------------------|
| status bar and panels          |
|--------------------------------|
```

would provide much more space to important information in panels and the status bar. Currently the file tree takes up all that space which I find very wasteful.

**Comment by simurai** [comment]
There is now an issue about allowing top/bottom bars in general: https://github.com/atom/atom/issues/8939

Once that is possible, it could be considered to change the status bar.

**Comment by simurai** [comment]
I tried out making the status-bar to take up full-width, like:

![screen shot 2015-10-03 at 10 20 49 am](https://cloud.githubusercontent.com/assets/378023/10260897/799a545e-69bb-11e5-9f63-0c756a11f1e2.png)

But somehow it feels wrong. I think the reason is because the status-bar changes based on the active editor and should somewhat stay connected to it. Full-width at the bottom it feels like it's something more global and less related to the active editor.

**Comment by jerone** [comment]
I disagree about that the status-bar should be connected (same width) to the editor. The status-bar can contain tiles that aren't necessary related to the editor. Besides, if I split the screen it doesn't split the status-bar too. Making the status-bar to the full width has my preference. :+1:

**Comment by pradyunsg** [comment]
I agree with @jerone, I would expect the status-bar to be full-width. And just in case, a conflagration won't hurt. :wink:

**Comment by nixpulvis** [comment]
I was kinda expecting to see this land with the release of 1.6, is that still the plan?

**Comment by 50Wliu** [comment]
This was added in #133 and at the current pace of development will be available in Atom 1.8.0 (it just barely missed 1.7.0, sorry about that).

**Comment by nixpulvis** [comment]
It's OK, this gives me an excuse to learn how to override the built in packages.

**Comment by Alhadis** [comment]
> But somehow it feels wrong. I think the reason is because the status-bar changes based on the active editor and should somewhat stay connected to it. Full-width at the bottom it feels like it's something more global and less related to the active editor.

100% agreed with this. I can see how many people would want the status-bar to be full-width, but it now feels more detached.

> And just in case, a configuration option won't hurt.

Seems to be a forgotten art in this day and age...

Time for a PR I suppose.

**Comment by Alhadis** [comment]
[Aaaand pull-request sent!](https://github.com/atom/status-bar/pull/152)

**Comment by Campanula** [comment]
![really](https://cloud.githubusercontent.com/assets/8176642/15928988/c3fa8ca4-2e7c-11e6-951c-d36b8c40f84b.png)

> And just in case, a configuration option won't hurt.
