### ISSUE TITLE
Version control modification counter causes overlapping text on the bottom toolbar

### ISSUE THREAD

**Issue by AnotherJoSmith** [atom/status-bar#92]
Here is what my bottom toolbar looks like when a file with no modifications is open:
<img width="721" alt="screen shot 2015-07-08 at 3 51 53 pm" src="https://cloud.githubusercontent.com/assets/3300109/8580624/9ef4e244-2589-11e5-8ee2-c53775b5ecf4.png">

But when I switch tabs to a file with modified lines and the version control modification widget is displayed, it looks like this:
<img width="724" alt="screen shot 2015-07-08 at 3 52 08 pm" src="https://cloud.githubusercontent.com/assets/3300109/8580636/b4eef18e-2589-11e5-9ce2-4b8ee6fe2cd2.png">

Switching between two files that have not been modified doesn't cause this issue. If I resize my window, it fixes the status bar and everything is displayed and truncated normally. I did the same test with the linter package disabled, it is not caused by that plugin.

This is on Atom 1.0 running on OS X.

**Comment by 50Wliu** [comment]
Does this still happen in safe mode (`atom --safe`)?

**Comment by benogle** [comment]
This might be a chrome rendering issue a la https://github.com/atom/atom/issues/4924

**Comment by 50Wliu** [comment]
No response, and the above issue has been closed, so closing.

@AnotherJoSmith if you are still experiencing this issue on the latest Atom version (currently 1.6.0), please comment here.
