### ISSUE TITLE
Squirrel icon should disappear after upgrade if user's clicked release notes

### ISSUE THREAD

**Issue by Alhadis** [atom/status-bar#96]
**Trivial nag:**
When an update's ready to be installed, the blue Squirrel icon appears in the status bar. If a user's already read the newest changes (probably by clicking on it), and then restarted Atom to install the upgrade, the rodent should rack off after.

Just a small thing I feel would benefit the overall UX a little if it were catered to. =)

**Comment by jerone** [comment]
Possible duplicates: https://github.com/atom/atom/issues/6922 & https://github.com/atom/release-notes/issues/36

**Comment by mnquintana** [comment]
Thanks @jerone! This does indeed seem like a duplicate of https://github.com/atom/release-notes/issues/36 – closing this out in favor of that issue.
